### ISSUE TITLE
Unable to discover the BBPOS Chipper 2X BT card reader on Android

### ISSUE THREAD

**Issue by kyleabens** [eventOneHQ/capacitor-stripe-terminal#27]
**Describe the bug**
I'm unable to discover the BBPOS Chipper 2X BT card reader on an Android device with beta.6.  Could have something to do with `discoveryMethod: DiscoveryMethod.BluetoothProximity`since according to Stripe [here](https://stripe.com/docs/terminal/readers/connecting/bbpos-chipper2xbt#discover-readers) the Android SDK does not support Bluetooth Proximity but does support Bluetooth Scan.  I tried changing to `discoveryMethod: DiscoveryMethod.BluetoothScan` and it still wasn't finding it.

**To Reproduce**
1. Follow the Android setup guide
2. Power on the BBPOS Chipper 2X BT
3.  Initialize the plugin
4. Discover readers

**Expected behavior**
The plugin should discover the BBPOS Chipper 2X BT on Android 

**Smartphone (please complete the following information):**

- Device: Android Pixel 2
- Version Android v10

**Additional context**
Works on iOS

**Comment by nprail** [comment]
On Android, the `discoveryMethod` option is just completely ignored since it isn't even an option in the native Android SDK code. So changing that won't matter. 

Does it work if you do simulated mode?

**Comment by kyleabens** [comment]
I tried that and still nothing.  I connected my Pixel 2 and launched it from Android Studio and all I saw in the log was 

```
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 103091274, pluginId: StripeTerminal, methodName: discoverReaders
V/Capacitor: callback: 103091274, pluginId: StripeTerminal, methodName: discoverReaders, methodData: {"simulated":true,"deviceType":0,"discoveryMethod":1}
D/StripeTerminal: class=Terminal message=discoverReaders
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 103091275, pluginId: StripeTerminal, methodName: addListener
V/Capacitor: callback: 103091275, pluginId: StripeTerminal, methodName: addListener, methodData: {"eventName":"readersDiscovered"}
W/olutions.urabl: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
    Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
V/Capacitor/StripeTerminal: Notifying listeners for event readersDiscovered
V/Capacitor/StripeTerminal: Notifying listeners for event readersDiscovered
V/Capacitor/StripeTerminal: Notifying listeners for event readersDiscovered
```

None of it makes sense to me and I don't see any errors.

**Comment by nprail** [comment]
@kyleabens Hmm, based on `Notifying listeners for event readersDiscovered`, the native code is, in fact, finding readers and sending them up to JavaScript. But it seems it gets lost somewhere. 

What do you see in your JS console?

**Comment by kyleabens** [comment]
Found the error:

```
E/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 18356 - Msg: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'discoverReaders' of undefined
    TypeError: Cannot read property 'discoverReaders' of undefined
        at PaymentMethodComponent.<anonymous> (http://localhost/main-es2015.js:16082:70)
        at Generator.next (<anonymous>)
        at http://localhost/main-es2015.js:15841:71
        at new ZoneAwarePromise (http://localhost/polyfills-es2015.js:973:33)
        at push../src/app/shared/payment-method/payment-method.component.ts.__awaiter (http://localhost/main-es2015.js:15837:12)
        at PaymentMethodComponent.discoverReaders (http://localhost/main-es2015.js:16061:16)
        at PaymentMethodComponent.<anonymous> (http://localhost/main-es2015.js:16053:22)
        at Generator.next (<anonymous>)
        at fulfilled (http://localhost/main-es2015.js:15838:58)
        at ZoneDelegate.invoke (http://localhost/polyfills-es2015.js:377:30)
```

**Comment by kyleabens** [comment]
I think I know what's happening, one moment while I adjust something in my code

**Comment by kyleabens** [comment]
I keep getting an error that says I need to initialize StripeTerminalPlugin before I do anything which I am doing.  Still trying to figure out what's going on.

```
E/Capacitor/Console: File: http://localhost/vendor-es2015.js - Line 18356 - Msg: ERROR Error: Uncaught (in promise): Error: StripeTerminalPlugin must be initialized before you can use any methods.
    Error: StripeTerminalPlugin must be initialized before you can use any methods.
        at StripeTerminalPlugin.ensureInitialized (http://localhost/vendor-es2015.js:142633:19)
        at StripeTerminalPlugin.discoverReaders (http://localhost/vendor-es2015.js:142637:14)
        at PaymentMethodComponent.<anonymous> (http://localhost/main-es2015.js:16081:70)
        at Generator.next (<anonymous>)
        at http://localhost/main-es2015.js:15841:71
        at new ZoneAwarePromise (http://localhost/polyfills-es2015.js:973:33)
        at push../src/app/shared/payment-method/payment-method.component.ts.__awaiter (http://localhost/main-es2015.js:15837:12)
        at PaymentMethodComponent.discoverReaders (http://localhost/main-es2015.js:16061:16)
        at PaymentMethodComponent.<anonymous> (http://localhost/main-es2015.js:16053:22)
        at Generator.next (<anonymous>)

```

**Comment by nprail** [comment]
Ah, yes. The initialization takes about a second and since the constructor is not async, you can't wait for it to complete. #25 will solve this problem by providing a static async `create` method which will return a `StripeTerminalPlugin` instance that has completed initialization. 

I'll be pushing that fix soon.

**Comment by nprail** [comment]
Okay, with beta 7, you can use the new async `create` method to initialize:
```diff
- const terminal = new StripeTerminalPlugin({ ... })
+ const terminal = await StripeTerminalPlugin.create({ ... })
```

**Comment by kyleabens** [comment]
I upgraded to beta 7 and now I get

```
E/Capacitor/Plugin: DiscoverReaders was canceled by the user
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$DiscoverReadersOperation.cancel$terminalsdk_release(BbposBluetoothAdapter.kt:471)
        at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter.cancelDiscoverReaders$terminalsdk_release(BbposBluetoothAdapter.kt:75)
        at com.stripe.stripeterminal.adapter.MasterAdapter.cancelDiscoverReaders$terminalsdk_release(MasterAdapter.kt:34)
        at com.stripe.stripeterminal.TerminalSession$DiscoverReadersOperation.startCancel$terminalsdk_release(TerminalSession.kt:588)
        at com.stripe.stripeterminal.callable.Cancelable.cancel(Cancelable.kt:28)
        at io.event1.capacitorstripeterminal.StripeTerminal.abortDiscoverReaders(StripeTerminal.java:231)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:521)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```

Still looking into what could be causing it.  But the good news is is that it's a different error :)

**Comment by kyleabens** [comment]
Ignore the error, I figured it out, it wasn't finding anything because I filter out any devices that are at 0% battery and for whatever reason it's reading my BBPOS at that level even though iOS reads it at around 90%.  I'll need to keep doing some testing but that was something that I found odd.  Other than that everything works as expected, thanks!

**Comment by nprail** [comment]
The Android SDK only supports the Bluetooth Scan mode which only returns the serial number of the device. So it won't show the battery level until you connect. I would think it would return `null` if the level is unknown but it might return 0 too.

**Comment by nprail** [comment]
I just checked, the `batteryLevel` is 0 while scanning. Unless you use proximity mode, in which case, it has the percentage. But proximity mode is only available on iOS. 

This is what the object will look like:
```javascript
{
  "batteryLevel": 0, // 0 just means unknown, if it were actually 0, it would probably be off
  "deviceSoftwareVersion": "unknown",
  "deviceType": 0,
  "serialNumber": "CHB679364725539"
}
```
